USE KODILLA_COURSE;

DROP TABLE IF EXISTS STATS;
CREATE TABLE STATS (
	STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    STAT_DATE DATETIME NOT NULL,
    STAT VARCHAR(20) NOT NULL,
    VALUE INT(11) NOT NULL
    );

COMMIT;

DROP VIEW IF EXISTS BESTSELLERS_COUNT;
CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BS_COUNT FROM BOOKS
WHERE BESTSELLER = TRUE;

COMMIT;

UPDATE BOOKS
SET BESTSELLER = FALSE
WHERE BOOK_ID IN (1,2,3,4,5);
COMMIT;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO
	BEGIN
		DECLARE NUMBER INT DEFAULT 0;
		CALL UpdateBestsellers();
		SELECT BS_COUNT FROM BESTSELLERS_COUNT INTO NUMBER;
        INSERT INTO STATS (STAT_DATE, STAT, VALUE) 
					VALUES(CURTIME(),'BESTSELLERS',NUMER);
    END$$
DELIMITER ;

COMMIT;

SELECT * FROM STATS;